site_name: 'SaaS Cookbook'
site_author: 'AWS'
site_url: 'https://https://aws-saas-factory.github.io/'
repo_name: 'aws-saas-factory/aws-saas-factory.github.io'
repo_url: 'https://github.com/aws-saas-factory/aws-saas-factory.github.io'
copyright: 'Copyright &copy; Amazon 2022'
nav:
- Home:
  - index.md
- 'By Compute':
  - eks.md
  - serverless.md
  - iot.md
- 'By Infra & Databases':
  - Infra: infra.md
  - Databases:
     - rds.md
     - dynamodb.md
- 'Tasks':
  - 'Anomaly Detection': anomaly-detection.md
  - 'Alerting': alerting.md
  - 'Troubleshooting': troubleshooting.md
  - 'Workshops': workshops.md
- about.md
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    logo: 'fontawesome/solid/file-invoice'
  font:
    text: 'Lato'
    code: 'PT Mono'
  palette:
    scheme: slate
    primary: orange
    accent: blue
  highlightjs: true
  hljs_languages:
  - yaml
  - json
  - bash
markdown_extensions:
- toc:
    permalink: true
- admonition
- codehilite:
    linenums: true
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
